# This is the settings file for Product Search Engine - interpreter.

# 0. Redis connection
redis_host: "127.0.0.1"
redis_port: "6379"

# 1. DB connection

log_db_conn_info: "host=127.0.0.1 port=5432 user=pse password=pse dbname=pse"
graph_db_conn_info: "host=127.0.0.1 port=5432 user=pse password=pse dbname=pse"

